M48
; DRILL file {KiCad 6.0.11+dfsg-1~bpo11+1} date mar 01 ago 2023 14:35:58
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-01T14:35:58-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1~bpo11+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X8.0Y97.0
X8.0Y11.0
X62.0Y97.0
X62.0Y11.0
T0
M30
