M48
; DRILL file {KiCad 6.0.11+dfsg-1~bpo11+1} date mar 01 ago 2023 15:36:02
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-01T15:36:02-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1~bpo11+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X4.5Y91.5
X4.5Y4.5
X57.5Y91.5
X57.5Y4.5
T0
M30
