M48
; DRILL file {KiCad 6.0.11+dfsg-1~bpo11+1} date lun 28 ago 2023 14:59:57
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-28T14:59:57-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1~bpo11+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X161.0Y-112.0
X161.0Y-137.0
X215.0Y-112.0
X215.0Y-137.0
T0
M30
